name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch
  pull_request:
    branches:
      - main  # Runs on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or personal access token from secrets

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t exril/backend:tag .

    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push exril/backend:tag
